services:
  go-env:
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ./tutorials:/workspace/tutorials
      - ./monitoring:/workspace/monitoring
    
    tty: true


    
      